### ISSUE TITLE
Don't build for android

### ISSUE THREAD

**Issue by sergey-miryanov** [underscorediscovery/luxe#126]
arm-linux-androideabi-strip libLuxeApp-v7.so
flow / android specifics { build_type: 'debug',
  install_location: 'preferExternal',
  libs: { native: { snow: 'snow' } },
  sdk_min: 10,
  sdk_target: 19,
  permissions: [ 'READ_EXTERNAL_STORAGE', 'INTERNET' ],
  certificate: '' }
flow / build - android - using ant at /opt/apache-ant/bin/ant
Buildfile: /Users/zerg/Source/HAXE/luxe-samples/5_components/bin/android.build/project/build.xml

BUILD FAILED
/Users/zerg/Source/HAXE/luxe-samples/5_components/bin/android.build/project/build.xml:11: Cannot find /Users/sven/dev/android-sdk/tools/ant/build.xml imported from /Users/zerg/Source/HAXE/luxe-samples/5_components/bin/android.build/project/build.xml

Total time: 0 seconds
flow / build - android - stopping because ant failed to build, exit code 1

real    2m49.125s
user    5m9.719s
sys 0m9.553s
Sergeys-MacBook-Pro:5_components zerg$

**Comment by facciocose** [comment]
As of today **ant** path and **android-sdk** path are still hardcoded. Are there any plans to make them configurable? ;)

**Comment by underscorediscovery** [comment]
They are configurable.
See http://snowkit.org/2014/10/29/quick-setup-guides-and-help/#androidspecificsetup

**Comment by facciocose** [comment]
Thanks, I missed that article.

BTW per project configuration is great but a system wide configuration file would be simple to maintain for this sort of things.

**Comment by underscorediscovery** [comment]
I thought I had added the link to the setup guide - but it isn't listed there.
I'll list both, and on the android setup specifics I'll also list the global option.
Glad you got it working then!

**Comment by mightymarcus** [comment]
Hi. I just tested flow for android build and it says "build.xml" not found.

flow / build - android - using ant at C:/Development/Apache Ant/bin/ant.bat
Buildfile: build.xml does not exist!
Build failed
flow / build - android - stopping because ant failed to build, exit code 1

Hope someone can help me.
