### ISSUE TITLE
NineSlice; size property ignores tweens

### ISSUE THREAD

**Issue by DjPale** [underscorediscovery/luxe#170]
For NineSlice - it is not possible to tween the size vector directly like this ```Actuate.tween(nineslice.size, 1.0, { x: 300, y: 300 });```. For a workaround, one has to manually update it via ```onUpdate``` event for the tween object.

**Comment by underscorediscovery** [comment]
https://github.com/underscorediscovery/luxe/commit/8038c341ccc1e720cd3dea28c4cb780728d84f88 should have fixed this as well
