### ISSUE TITLE
Beginning of sound is skipped sometimes on mac

### ISSUE THREAD

**Issue by longears** [underscorediscovery/luxe#210]
When a sound begins to play it skips the first millisecond or so.
If the sound is already in the process of playing and play() is called again, it plays from the very beginning.
But once it gets to the end and stops, the next play() will again skip the beginning.

In this example, press space to play a bell sound.  If you press space several times a second you can hear the louder first part of the sound.  If you press space every 3 seconds you only hear the quieter second half of the sound.

This happens independently for each sound file, regardless of the playing-state of any other sound files.

Bug happens on Mac native build (tested on OSX 10.8.5).  Works fine on web build.

```
class Main extends luxe.Game {
    override function ready() : Void {
        Luxe.audio.create('assets/bell.wav', 'bell');
        Luxe.audio.on('bell', 'end', function(_) {
            trace('  sound ended');
        });
    }
    override function update(dt : Float) {
        if (Luxe.input.keypressed(luxe.Input.Key.space)) {
            trace('started sound');
            Luxe.audio.play('bell');
        }
    }
}
```

Get `bell.wav` from
http://birdhat.org/misc/bell.wav

Or a zip file of the whole source directory here
http://birdhat.org/misc/haxe-luxe-soundbug.zip

**Comment by underscorediscovery** [comment]
I tested this against the latest snow alpha-2.0 and luxe code and I don't hear any skipping as described, if you're inclined can you test against [the latest updates](https://snowkit.org/2016/02/15/snow-alpha-2-0-changelog/) and let me know? 

Two notes:
- The sound file in the zip file was 32 bit float, which isn't supported as is, so I exported it from audacity as a regular 16 bit wav instead and it loaded up.
- The recent updates changed the audio API slightly, so I included the updated code below :

```haxe
import luxe.resource.Resource;

class Main extends luxe.Game {

    var sound : AudioResource;

    override function config(config:luxe.AppConfig) {
        config.preload.sounds.push({ id:'assets/bell.wav', is_stream:false });
        return config;
    }

    override function ready() : Void {
        sound = Luxe.resources.audio('assets/bell.wav');
        Luxe.audio.on(ae_end, function(_handle:snow.types.Types.AudioHandle) {
            trace('  sound ended $_handle');
        });
    }
    override function update(dt : Float) {
        if (Luxe.input.keypressed(luxe.Input.Key.space)) {            
            var _handle = Luxe.audio.play(sound.source);
            trace('started sound $_handle');
        }
    }
}
```
