### ISSUE TITLE
App crashes on android on immediate start after closing with Luxe.shutdown()

### ISSUE THREAD

**Issue by JeriXNet** [underscorediscovery/luxe#215]
App was launched normally through icon on main screen. Then on user interaction was called `Luxe.shutdown()` and app closed. After that I tried to restart the app again and it didn't start: some black flashing appeared and there was no error window. It starts normally after removing launched activity from recent app list.
Some time ago I had the same issue in my day job project. I was using SDL too and made that dirty fix with calling `exit(0)` in the end of my `SDL_main()`

**Comment by underscorediscovery** [comment]
should be resolved short term with this commit https://github.com/underscorediscovery/snow/commit/6beb5bf
