### ISSUE TITLE
NineSlice ignores scale and transform.parent scale

### ISSUE THREAD

**Issue by whuop** [underscorediscovery/luxe#222]
Setting the parent transform of a nineslice or setting the scale directly of the nineslice does not change the scale of the nineslice. The scale stays the same. For example, scaling up a nineslice does not scale up the graphics that is used for the nineslice.

**Comment by anissen** [comment]
Solved in https://github.com/underscorediscovery/luxe/pull/217 :cake:

**Comment by underscorediscovery** [comment]
I'll get on merging this soon enough, once alpha 2 is up and posted.
