### ISSUE TITLE
Resource; id overrides

### ISSUE THREAD

**Issue by underscorediscovery** [underscorediscovery/luxe#233]
- [x] ~~resources can have a id or name property for querying instead~~
   - ~~i.e `find('assets/font.fnt')` vs `find('font.customid');`~~
- [x] ~~resource cache query by id and by name~~

--- 

alpha-2.0 notes: due to the nature of resources, id's are the better option. Any id remapping can be done at the application level with minimal effort, but I don't want to encourage obfuscation of information and especially convolute the id apis, especially when it comes to tagging soon.

**Comment by FuzzyWuzzie** [comment]
woot woot!
