### ISSUE TITLE
touch_id on iOS and features/touch_events crash

### ISSUE THREAD

**Issue by haxiomic** [underscorediscovery/luxe#242]
The format of touch_id differs between platforms, consequently the test [features/touch_events](https://github.com/underscorediscovery/luxe/blob/master/tests/features/touch_events/src/Main.hx) crashes out on iOS

On web and Android it appears the touch_id ranges from 0 to max-touches and is arranged by the of the touches arriving

whereas on iOS touch_id is some arbitrary value with no clear relationship to the order of touches arriving (it's some int64_t value in SDL which arrives in haxe as an Int, usually something like 2039369120 or -1671352981). In [features/touch_events](https://github.com/underscorediscovery/luxe/blob/master/tests/features/touch_events/src/Main.hx), the touch_id is used as an index to select a color, expecting it be a value ranging from 0-5, colors[touch_id] returns null, .clone() is called on this causing the crash.

Should touch_id be forced to conform to a simple index on all platforms (snow-side) or should the current behavior be kept and just the test fixed?

The fix so that iOS has the same behavior as web and android looks something like
````haxe
    var touches = new Array<Null<Int>>();

    function add_touch(touch_id:Int) : Void {
        var i = touches.indexOf(null);
        if(i > -1)  touches[i] = touch_id;
        else        touches.push(touch_id);
    }

    function remove_touch(touch_id:Int) : Void {
        touches[touches.indexOf(touch_id)] = null;
    }

    function get_touch_index(touch_id:Int) : Int {
        return touches.indexOf(touch_id);
    }
````

where ```add_touch``` is called ontouchdown and ```remove_touch```, ontouchup. get_touch_index(touch_id) will have the same behavior on all platforms independent of touch_id

Perhaps we could add a  ```.touch_index``` field to TouchEvent or just replace the value of touch_id

**Comment by haxiomic** [comment]
[Modified features/touch_events with iOS fix](https://gist.github.com/haxiomic/b0128482fa1d8dfbced0)

**Comment by underscorediscovery** [comment]
Hmm - the general definition of the touch id is a guarantee that the `touch_id` will remain the same for _that_ touch and that subsequent events (move, up) will always match. The value is similar to the concept of a timestamp where the differences make sense and the value itself might be different.

The pass through from int64_t to Int is probably what causes the negative number (I suspect that the SDL intends it to be unsigned and it's wrapping on `Int`? Not sure, will check). 

Mainly, 

1. I don't want to process touches further than they need to be, as _any_ added overhead/latency on input is bad for the engine to be doing.
2. I wrote the touches test real quick specifically for testing web touch events, I hadn't tested on mobile (yet)

Short term, I think the test should just do :

`var touches:Map<Int, Int>;`
down:
`touches.set(event.touch_id, Lambda.count(touches))`
up:
`touches.remove(event.touch_id)`
and "get color id":
color = colors[touches.get(event.touch_id)];

That will fix the test and give a usage pattern that normalizes the touch id's input, and the user opts into the overhead explicitly.

We can explore other options from there.
