### ISSUE TITLE
font asset not found

### ISSUE THREAD

**Issue by yupswing** [underscorediscovery/luxe#244]
When I try to run the 4th guide I get a "not found" error and it stops on the loading progress bar.
I've noticed that trying to run this https://github.com/Eiyeron/-SQUARE- (same problem) so I've checked the official repo example to confirm the problem.

Is something changed in the api/parcel.json/project.flow or is it a bug?

I am not even sure it is a LUXE problem. Probably a SNOW one (I don't think a FLOW one because in the build the fnt file is included).

Thanks for this good work, keep it going man, it's brilliant!

```
flow / build - done
flow / launching luxe - guide - text and tweening 1.0.0 for mac

Core.hx:97:      i / luxe / version 1.0.0-alpha.1+4bc869b0e5
Parcel.hx:111:    i / parcel / starting load
Texture.hx:149:   i / texture / loaded assets/apartment.png (254x169) real size (254x169)
Assets.hx:309:    i / assets / not found "montez.fnt"
Core.hx:134:      i / luxe / shutting down...
Core.hx:166:      i / luxe / goodbye.
Snow.hx:351:      i / snow / Goodbye.
```

**Comment by underscorediscovery** [comment]
Its a recent change in fonts specifically. They now use the asset id from the font rather than the face name.
For example, assets/fonts/montez.fnt instead of montez.

I'll check the guides are updated for the change, thanks.

**Comment by yupswing** [comment]
brilliant. so fast. cheers
