### ISSUE TITLE
Scene; calling empty() causes erroneous log output  

### ISSUE THREAD

**Issue by anissen** [underscorediscovery/luxe#255]
When calling `scene.empty()` I get the following trace:
```
Entity.hx:517:    i / entity / entity has no parent or scene, currently no core events will reach it.
```
The reason, as far as I can gather, is as follows:

In Scene::empty(), this happens:
```haxe
remove( entity );
entity.destroy();
```
Where `remove()` sets the `scene` of `entity` to `null`. 

Then, `entity.destroy()` triggers the following function calls on `Entity`:

* `destroy()`
  * `onremoved()`
    * `_unlisten()`
      * `_find_emit_source()` which has the following code:

```haxe
        if(scene != null) {

            source = scene;

        } else if(parent != null) {

          // ...

        } else {
            log('entity has no parent or scene, currently no core events will reach it.');
        }
```
Because the `entity`'s `scene` variable was set to `null`, the `log`-statement will be outputted.

**Comment by underscorediscovery** [comment]
ah, yep that's not right, will fix that thanks!
