### ISSUE TITLE
tests/features/quadpack_geometry exceeds the maximum vert count

### ISSUE THREAD

**Issue by drezabek94** [underscorediscovery/luxe#259]
Running the example `tests/features/quadpack_geometry` causes the following exception to be throw:
"Currently a single geometry cannot exceed the maximum vert count of 32768"
from Geometry.hx

The issue lies in the example's Main.hx, on line 95:
```haxe
var tilew = 8;
```
Changing that to a larger number, say 16, creates larger tiles, and fills up the screen with smaller number of tiles as a result, so that the maximum vertices count isn't reached.

**Comment by underscorediscovery** [comment]
yep, I'm aware thanks!
