### ISSUE TITLE
Error : Could not load module snow@snow_iosrc_file_read__4

### ISSUE THREAD

**Issue by alesegdia** [underscorediscovery/luxe#261]
I'm using Ubuntu 14.04 and I get this on trying to build anything to linux target (web runs ok). Anyone with Linux running it well?

```
$ haxelib run flow run linux
flow / 1.0.0-alpha.1
flow / target is linux ( arch 64 )
flow / haxe version 3.1.3

flow / project - searching project root /home/me/project
flow / project - using project file /home/me/project/project.flow
flow / build - empty 1.0.0 for linux
flow / no icon convert just yet for linux

flow / build - running haxe ...
flow / build - running hxcpp for arch 64 ...
flow / build - done
flow / launching empty 1.0.0 for linux

Error : Could not load module snow@snow_iosrc_file_read__4
```

**Comment by underscorediscovery** [comment]
Is that using the latest builds from http://build.luxeengine.com/snow ?

**Comment by alesegdia** [comment]
I installed it by following the steps at luxe setup docs, so it's git version.

**Comment by underscorediscovery** [comment]
The steps from the luxe setup guide include this step, I need to confirm if you are using the ones from there, so I can test the right version against my own linux machine :)

**Comment by alesegdia** [comment]
Oh, sorry. Now it works! Didn't check about the blog post and pasted it inside my project folder. Now I wish issues could be deleted from github. :(

**Comment by underscorediscovery** [comment]
That's really ok! You can blame me because you had to read a blog post and copy some files during alpha :)

_If you really want, I can delete all the replies, and you can edit the original message, but it does no real harm to keep it here).

**Comment by alesegdia** [comment]
Well, it may serve for another piece of dumb meat like me, so we can leave it here! :)
