### ISSUE TITLE
Luxe lacks code conventions (code standards)

### ISSUE THREAD

**Issue by frenetic** [underscorediscovery/luxe#266]
N00b here, trying to learn Luxe o/

Reading the "begginers guide" I couldn't stop noticing this framework lacks code conventions, code standard or code consistency.
Even though it's not a major bug, this behaviour may lead newcomers to confusions.

Exemple:
- Scene class (https://github.com/underscorediscovery/luxe/blob/master/luxe/Scene.hx) has methods on lowercase and methods on snake_case
- All methods on Game class are lowercase, but all methods on Physics class are snake_case.
- Your tween Actuate class (https://github.com/underscorediscovery/luxe/blob/master/luxe/tween/Actuate.hx) is all in camelCase. But the tween MotionPath class is snake_case (https://github.com/underscorediscovery/luxe/blob/master/luxe/tween/MotionPath.hx)
- ParcelPrograss.hx has a method named **oncomplete** (https://github.com/underscorediscovery/luxe/blob/master/luxe/ParcelProgress.hx#L153), Audio.hx has it named **on_complete** (https://github.com/underscorediscovery/luxe/blob/master/luxe/Audio.hx#L92), genericActuator.hx has it **onComplete** (https://github.com/underscorediscovery/luxe/blob/master/luxe/tween/actuators/GenericActuator.hx#L213) 
- Tween classes, like Back.hx has methods that mix snake_case with camelCase: **get_easeIn** (https://github.com/underscorediscovery/luxe/blob/master/luxe/tween/easing/Back.hx#L19)

It would be nice if all class methods followed the same code convention.

**Comment by underscorediscovery** [comment]
Yep, this will happen over time as we progress through alpha, and is expected in code that is not complete.

Some code is also third party (like Actuate) and new code (mentioned in the devlogs, Delta) will be consistent. You'll even find issues filed for fixing consistency in various places already, btw. You might even already find some code format standards in the snow docs (which is outdated anyway). 

One step at a time :)

p.s There are actually conventions and standards, and those will be formalized when the code is clearer, but in reality I am just not the type of developer where different cases make the code somehow less useful in practice. I have high standards, and I have issues with inconsistency, but semantics do not prevent _results_ and _output_, which matter more to me than text formatting at the end of the day.

**Comment by frenetic** [comment]
This doesn't break anything nor block other developers from using the framework.
But, as I said, it would be nice to have one single code convention.

Also, I agree with your PS: people buy apps and games, node the quality code behind them :P

**Comment by underscorediscovery** [comment]
Yea, I'm interested in code consistency, but I am realistic about it, and I prefer to move things as a sliding scale rather than trying to reach some standards before the code is even done. It just gets in the way of allowing others to contribute or leveraging existing work. 

In the end - if you had used Actuate externally, your usage code is still "inconsistent" because you could never expect an entire language and it's frameworks to conform to some singular ideal, that's not how programming works. So even if all the luxe code was 100% right now, any library you use puts you back in the same place, and every library after that, another place. You'll always be in the same situation, somewhere :)

**Comment by underscorediscovery** [comment]
I'll make some quick notes about the general direction in a bit though for clarity, just fixing some bugs for LD.

**Comment by frenetic** [comment]
Thanks! :)
You are a really cool community leader!
