### ISSUE TITLE
Tilemap refresh_tile_id doesn't update the corresponding Tile's _id

### ISSUE THREAD

**Issue by joekinley** [underscorediscovery/luxe#271]
What the title says. 
If I use a tilemap.visual.refresh_tile_id(...), to update the new tile. Imagine this code (not tested, just showing)

```
// the current tile's id is 1, newTile is 2
this.tilemap.visual.refresh_tile_id(FLOOR_LAYER, xPos, yPos, newTile); // this changes the visual of my tile to the 2nd tile ID
...
// now to check the tile id
var newId:Int = this.tilemap.tile_at(FLOOR_LAYER, xPos, yPos).id; // returns still 1, and NOT 2 how it would have been expected
```

**Comment by underscorediscovery** [comment]
Actually, you should be changing the tile id, not calling the function on the visual.

See for example, the test case:
https://github.com/underscorediscovery/luxe/blob/master/tests/features/tiles/src/Main.hx#L87-L93

And the documentation on `refresh_tile_id`:
>  This is called automatically when you set a `Tile` ID in a map, if it has a visual assigned.

The usage pattern is not intended to modify the tile id, it's the other way around at this point :)

**Comment by joekinley** [comment]
Ooh look that works. Thanks =)
