### ISSUE TITLE
Strange behaviour and poor error messages with SpriteAnimations.

### ISSUE THREAD

**Issue by NicoM1** [underscorediscovery/luxe#273]
ok, so instead of creating a sample for this, I figured the easiest way to show the (semi) issue is by showing what to change in the 3-sprite-animations guide code. Basically, the first, kinda odd but not terrible behaviour is the fact that if you add a spriteanimation without initializing it somehow, the game will crash with an error from the set_frame method, not very helpful, and seems odd if they are separate that you are forced to ensure you both create and initialize them at the same time. 

The stranger issue, and the one that made me unable to build for several days (admittedly due to my bad debugging and having other stuff I could work on) is the fact that if you do no specify an animation (anim.animation = 'name') alongside when you create the animation, it will also fail, again with the same error, and again super unhelpful and untraceable.

Note: it *does not matter* if you do anything with the animation after, ie. even if you never attempt to play the animation or do anything, this will still cause a crash.

```
 function create_player_animation() {
        
        var anim_object = Luxe.resources.json('assets/anim.json');

        anim = player.add( new SpriteAnimation({ name:'anim' }) );

        anim.add_from_json_object( anim_object.asset.json ); //commenting this out will cause a crash

        anim.animation = 'idle'; //commenting this out will cause a crash
        anim.play();

    } 
```

**Comment by NicoM1** [comment]
just to be clear, even if you remove that play() and all other code in the demo other than the necessary setup for this, it will still crash.

**Comment by underscorediscovery** [comment]
There was an error message - it was the null reference, it had a full stack trace (exact line number, function name, class, file name) in debug mode. 

```
Called from luxe.components.sprite.SpriteAnimation::set_frame luxe/components/sprite/SpriteAnimation.hx line 373
Error : Null Object Reference
```

A very simple error fixed in seconds, given an error log or an isolated test (or a hyperbolical description so I can run into it :P).

Thanks for the report.
https://github.com/underscorediscovery/luxe/commit/7a05aef221769758b7a8b404ce4a93a1c997e813
