### ISSUE TITLE
Entity.init called twice on setting parent

### ISSUE THREAD

**Issue by joekinley** [underscorediscovery/luxe#274]
I have an entity that I create in my code, and manually set the parent:
```
this.inventory = new Inventory();
this.inventory.parent = this;
```
Where Inventory is extending Entity.
When uncommenting the parent setting, the init function of the Inventory is only being called once. Though, setting the parent, it is being called twice.

Workaround: I have to manually add a guard at the top of the init function
```
if(this.inited) return;
```

Is this on purpose? I kinda doubt it, but I may be wrong there.

**Comment by underscorediscovery** [comment]
It's obviously not intended to call twice, but I won't make any assessments without reproducible code.

It could be a side effect of [this](https://github.com/underscorediscovery/luxe/commit/47740ff94ce9eb5c3494a412ebcd54a7785cf714) recent change, but if you can give me something tangible to test that would be ideal.

**Comment by joekinley** [comment]
Well I try to, apparently it is not as straightforward as I assumed it would be, to reproduce.
BUT that recent change did NOT cause this behavior. 

I keep trying to make reproducible code.

**Comment by joekinley** [comment]
Okay so here is how far i've gotten up to today:
* This only happens from Scene.handle_delayed_additions
* Only seems to happen when I set the parent of an Entity
* Apparently checking for "this.inited" is not always reliable either

I have yet to figure out how to get my example-code to get into the delayed additions for it to happen. Because there it happens. 

Regardless of all this, it would be helpful (I assume) if the Scene.handle_delayed_additions function checks for inited state before calling init() on the children again?

**Comment by Zielak** [comment]
Hey, have you tried setting parent from the constructor?
`this.inventory = new Inventory({parent: this});`

**Comment by joekinley** [comment]
Not yet, will try tonight

**Comment by Zielak** [comment]
It should be available if you're using standard Entity's `new() ` constructor.

**Comment by underscorediscovery** [comment]
> checks for inited state before calling init() on the children again?

My problem with doing these type of bandaid fixes is that if there is an actual bug related to how they are getting in there more than once, we just brushed it under a rug.  

If you can't find why it's happening but you do have a reproducible case - you can email or message me a link to the source, like in pm on the chat. I can have a look at that as well.

**Comment by underscorediscovery** [comment]
Thanks for the link on PM @joekinley, I debugged the code from your web build and found the behaviour I was looking to confirm.

This should be resolved if you update to the commit below.

https://github.com/underscorediscovery/luxe/commit/d0659afff46e4e687fb45a5e4c3927c206de706c
