### ISSUE TITLE
Infinite recursion when setting entity.parent = entity

### ISSUE THREAD

**Issue by Aleph0Null** [underscorediscovery/luxe#277]
There should be a guard against this in `Entity`'s `set_parent()`. I'd make a pull request, but I'm not sure how you want to handle such errors.

Also, `_add_child()` should be private, and `children` shouldn't have public write access. Again, sorry if you're already aware of all this, I know things are in the works right now.

Edit: More generally, there needs to be some way of preventing/dealing with circuits in the parent-child relationship graph. A `grandparents()` function that walks through parents could be handy.

**Comment by underscorediscovery** [comment]
https://github.com/underscorediscovery/luxe/commit/a189ad2017cb985d62f79c5f5bd6d652a0d9b912

Also _add_child was hidden with `@:noCompletion`, it was semi private at one point. As with a lot of other things. Sometimes I prefer things to be accessible by users that want to bypass the internal stuff and construct there own, without hacking in the core.

It's usually only a problem If you're using flash develop - for some reason it ignores these haxe features and shows them anyway. For now I switched them to more fine grained control.
