### ISSUE TITLE
Nape physics debug draw; ignoring shape.localCOM; all shapes center middle

### ISSUE THREAD

**Issue by alesegdia** [underscorediscovery/luxe#282]
Tried to fix it by adding offset without success at https://github.com/underscorediscovery/luxe/blob/master/luxe/physics/nape/DebugDraw.hx#L243

**Comment by KeyMaster-** [comment]
Could you provide some example code of what exactly you're doing? I tried creating some shapes, changing their COMs and adding them to bodies, and they seem to draw fine.

**Comment by alesegdia** [comment]
The body has a bottom displacement of 8: https://github.com/alesegdia/evoswonie/blob/master/project/src/entity/Player.hx#L112

Adding the body to the physics debug drawer: https://github.com/alesegdia/evoswonie/blob/master/project/src/entity/GameWorld.hx#L16

You can see the debug circle is drawn in the center, but it collides a little lower as expected.

http://alesegdia.github.io/vswn/

**Comment by KeyMaster-** [comment]
Should be fixed in f39e5f01e848412102be33e80e8010304a7178a7.
Small tip on the side: For nape vectors, you'd generally use `Vec2.get()` / `Vec2.weak()` instead of `new Vec2()`. Just noticed it while looking at the code.
