### ISSUE TITLE
Tiled; Object layers support for importer

### ISSUE THREAD

**Issue by alesegdia** [underscorediscovery/luxe#283]
Object layer format example (json just for rectangles): https://github.com/alesegdia/evoswonie/blob/master/project/assets/test-airplat-floorplat.json#L47-103

Official specs: http://doc.mapeditor.org/reference/tmx-map-format/#objectgroup

**Comment by underscorediscovery** [comment]
Would you mind including links to the specific format specification node you're referring to? 

There are already some things parsed by the Tiled parser that don't necessarily automatically "show" and are data only - it would be good to have the distinction clarified :)

**Comment by alesegdia** [comment]
I just updated the issue description to point to an example of mine and official specs. I'm currently using only rectangles and the format I use is .json, but the official specs are explained for tmx format.

**Comment by underscorediscovery** [comment]
Ok, so can you tell me if there is a problem in them here?

https://github.com/underscorediscovery/luxe/blob/master/luxe/importers/tiled/TiledObjectGroup.hx

**Comment by alesegdia** [comment]
Aww!! perfect, this is what I was looking for, sorry! I'm colsing this.

**Comment by underscorediscovery** [comment]
Not a problem!
