### ISSUE TITLE
"Standard Library not found" when attempting test mentioned in installation instructions

### ISSUE THREAD

**Issue by makoConstruct** [underscorediscovery/luxe#291]
On 64 bit linux, with a fresh neko install (from source) the test recommended here http://luxeengine.com/docs/setup.html (`cd /path/to/luxe/tests/features/draw/ &&  haxelib run flow run web`) fails with

```
flow / 1.0.0-alpha.1
flow / target is web 
flow / haxe version 3.2.0

flow / build - luxe.draw 1.0.0 for web
flow / build - running haxe ...
Standard library not found
```
What could that be referring to? I *have* haxe, it could not get this far without having haxe.

If it's any help, the error seems as though it could only originate here https://github.com/HaxeFoundation/haxe/blob/2c07c48f00dcf56dbb81a2164669f99a37e8c64f/typer.ml#L5065

**Comment by underscorediscovery** [comment]
I think if you manually install haxe you have to define it's variables like HAXE_STD_PATH and HAXE_HOME and NEKOPATH, there are some results about it [that seem similar](http://stackoverflow.com/questions/26826885/haxe-cant-find-std-libraries)

Also you could check [this script](http://www.openfl.org/builds/haxe/), which does an install for ubunt-similar distros, which you could just use to set up haxe or it may give you a hint as to some missing config or variable in your case.

**Comment by makoConstruct** [comment]
The install script seems to have worked! Suxu, _discovery..

I notice there's no anti-aliasing on the primitives in the draw demo. Is there anything I can do about that or.. should I be going to OpenFL for that kind of functionality?

**Comment by underscorediscovery** [comment]
The only kind available out of the box is [MSAA](https://en.wikipedia.org/wiki/Multisample_anti-aliasing).

Enable it from the `render` `config` node. 
Take one of the tests for example, and edit the `config` function, [inside it add the following line](https://github.com/underscorediscovery/luxe/blob/master/tests/features/draw/src/Main.hx#L34-L40):

`config.render.antialiasing = 4;`

The value can be 2,4,8,16 etc but the actual value available will depend on your hardware availability. Setting it too high might cause the window creation to not work (especially on linux, which is an issue that will be resolved soon enough).
