### ISSUE TITLE
Class should be String errors in FlashDevelop

### ISSUE THREAD

**Issue by davisable** [underscorediscovery/luxe#295]
In FlashDevelop (5.0.1.3), I'm seeing the following message pop up repeatedly in the Output window when working with Luxe projects:

    --macro:1: character 0 : Class<snow.modules.interfaces.Audio> should be String
    --macro:1: character 0 : { } should be String
    --macro:1: character 0 : For function argument 'module'

I have a feeling this is interfering with code completion in FD also as it seems to popup more frequently when using code completion. Any suggestions on what this could be?

**Comment by underscorediscovery** [comment]
@davisable and others, 

Following the discussion and fixes [here](https://github.com/Chman/Snowkit-FD/issues/8),

http://www.flashdevelop.org/community/viewtopic.php?f=9&t=3529

Please let us know if that's better.
