### ISSUE TITLE
Favicon is unoptimized

### ISSUE THREAD

**Issue by davisable** [underscorediscovery/luxe#296]
Just a minor thing I noticed: the default favicon.png included in the Luxe web build is 19KB even though it's only 64x64px.

Running it through a PNG compressor like tinypng results in the default favicon.png going to ~1KB with 0 loss in quality : http://i.imgur.com/HMhzw2I.png

**Comment by underscorediscovery** [comment]
I pushed the optimized one thanks https://github.com/underscorediscovery/luxe/commit/6da18ecf388a6269bbb289cb8055fa448d1ac598
