### ISSUE TITLE
Assets with custom IDs

### ISSUE THREAD

**Issue by oxysoft** [underscorediscovery/luxe#303]
Is it possible? For example:

Currently:

    config.preload.textures.push({ id: 'assets/graphics/thing.png' });

    ...

    Luxe.resources.texture('assets/graphics/thing.png')

What I'd like:

    config.preload.textures.push({ id: 'thing', path: 'assets/graphics/thing.png' });

    ...

    Luxe.resources.texture('thing')

Thanks

**Comment by underscorediscovery** [comment]
For now you would just maintain your own map. 
I prefer not to create ambiguity in the id's directly (dev log one touches on the idea of tags a little, but a future dev log should elaborate why I think this is a bad idea).

```haxe
var asset:Map<String,String>;

override function ready() {

  asset = new Map();
  asset.set('thing', 'assets/graphics/thing.png');

 ...

 Luxe.resources.texture(asset('thing'));

}

```

You can load the mapping from JSON or make it static and assign them directly. You could also make a strong typed class with a getter for every asset id, and go as far as generate all of those by macros :) It's up to you to pick the workflow that fits best, and the resource manager remain consistent and predictable across all targets.
