### ISSUE TITLE
TiledMap; Add support for tile flipping

### ISSUE THREAD

**Issue by oxysoft** [underscorediscovery/luxe#304]
Below is a zip archive containing a test project with some flipped tiles in a tmx map

https://hostr.co/l7YccQztqCFd

The tiles are all '0' tiles except for four which are the '1' tiles, flipped in every four possible configurations (none, x, y, xy)

Look at the details.png file in the assets folder for a more visual description

**Comment by underscorediscovery** [comment]
:envelope_with_arrow:

**Comment by KeyMaster-** [comment]
Closed with 163eef25e9a96055c9b3925f5f0e62fdac251eda which adds flipping and tile rotation support. If you find any issues please report them :)
