### ISSUE TITLE
bin/linux.build/haxe/LuxeApp.hx:1: characters 7-11 : Type not found : Main

### ISSUE THREAD

**Issue by raould** [underscorediscovery/luxe#314]
happens for pretty much any target I try (linux, ios, web)

```
$ pushd `haxelib path luxe|head -1`
/usr/lib/haxe/lib/luxe/git ~/Dev
$ haxelib run flow run web
flow / 1.0.0-alpha.1 (node.js v0.12.7)
flow / target is web 
flow / haxe version 3.2.0

flow / build - luxe 1.0.0-alpha.1 for web
flow / build - running haxe ...
bin/web.build/haxe/LuxeApp.hx:1: characters 7-11 : Type not found : Main
```

Ubuntu 14.04 x86
actuate: [1.8.6]
away3d-examples: [1.1.0]
away3d: [1.1.0]
flow: 0.0.0 git [dev:/usr/lib/haxe/lib/flow/git]
format: [3.1.2]
hamcrest: [2.0.0]
HaxePunk: [2.5.6]
hxcpp: [3.2.102]
jQueryExtern: [2.0.4]
lime-samples: 2.3.0 2.5.1 [2.6.0] 2.4.0
lime: 2.5.2 2.5.1 [2.6.1] 2.4.9 2.4.8
luxe: 0.0.0 git [dev:/usr/lib/haxe/lib/luxe/git]
mconsole: [1.6.0]
mcover: [2.1.1]
mlib: [2.0.2]
munit: [2.1.0]
nme: [5.4.2]
openfl-ouya: [1.0.2]
openfl: 3.1.2 [3.2.0] 3.1.3 2.2.4
poly2trihx: [0.1.4]
promhx: [1.0.21] 1.0.20
snow: 0.0.0 git [dev:/usr/lib/haxe/lib/snow/git]
thx.core: [0.31.0]
thx.unit: [0.4.1]
tink_core: [1.0.0-rc.11]
tink_lang: [0.3.1]
tink_macro: [0.6.4]
tink_priority: [0.1.2]
tink_syntaxhub: [0.3.3]

**Comment by underscorediscovery** [comment]
What folder are you running the command in? Did any of the samples/tests run? Like the one in the setup guide?

**Comment by raould** [comment]
/usr/lib/haxe/lib/luxe/git/tests/three/mesh$ haxelib run flow run web
flow / 1.0.0-alpha.1 (node.js v0.12.7)
flow / target is web 
flow / haxe version 3.2.0

flow / build - luxe.mesh 1.0.0 for web
flow / build - running haxe ...
bin/web.build/haxe/LuxeApp.hx:45: lines 45-49 : { has_loop : Bool, config_path : String, app_package : String } has extra field config_path

**Comment by underscorediscovery** [comment]
Sounds like you have an outdated `snow` at minimum. Can you try `haxelib update snow` or if that doesn't update, `cd /usr/lib/haxe/lib/snow/git && git pull` ?

**Comment by raould** [comment]
That fixed it, thanks!

I'm surprised since I don't think I installed snow all that long ago ;-) but hooray! :-)
07f50e2..bb75e3d

**Comment by underscorediscovery** [comment]
Great :) If you run into errors in future, first check the commit log - I try to make it [very clear](https://github.com/underscorediscovery/luxe/commit/37edfa0bf3e31c9bb5784b8c5fb4d0038a1b6e58) in the logs while we work through the alpha

**Comment by raould** [comment]
Yeah, understood, thanks for continuing on Luxe!
