### ISSUE TITLE
Error : Could not load module snow@snow_iosrc_file_read__4

### ISSUE THREAD

**Issue by raould** [underscorediscovery/luxe#315]
web target works.
linux target doesn't.

```
/usr/lib/haxe/lib/luxe/git/tests/features/draw$ haxelib run flow run linux
flow / 1.0.0-alpha.1 (node.js v0.12.7)
flow / target is linux ( arch 32 )
flow / haxe version 3.2.0

flow / build - luxe.draw 1.0.0 for linux
flow / no icon convert just yet for linux

flow / build - running haxe ...
flow / build - running hxcpp for arch 32 ...
flow / build - done
flow / launching luxe.draw 1.0.0 for linux

Error : Could not load module snow@snow_iosrc_file_read__4
```
That's the short version because i already ran the build once. No errors were reported when building that I see. I literally just did the flow, snow, luxe update 10 mins ago. Just double-checked, "Already up-to-date" for all 3 of them.
Ubuntu 14.04 x86

**Comment by underscorediscovery** [comment]
Did you install the required native binaries? 

http://luxeengine.com/docs/setup.html#step4

**Comment by raould** [comment]
No, I missed that part of the installation. I'm starting to really understand what you mean by 'alpha' ;-). I would urge you to pause to write an installer script. I know it sucks, I know it doesn't feel like real work, but this is the kind of bumps in the road that turns people away -- or ends up with silly people like me opening annoying issues. :-) 

That fixed it, thanks!

**Comment by underscorediscovery** [comment]
I don't disagree that there are bumps, but those aren't wholly involved here. No amount of magic buttons will solve people skipping sections or not reading things carefully :)

**Comment by underscorediscovery** [comment]
p.s 
[There is an installer](https://dl.dropboxusercontent.com/u/736396/luxe_installer.gif), but it's not the right time for that, it creates an illusion of completion that I'm not comfortable with at the moment. I prefer the clarity.

**Comment by raould** [comment]
sure thing, thanks for the cool project. i hope i can do it justice with my lame game stuff.
