### ISSUE TITLE
(subjective) import style breaks .*

### ISSUE THREAD

**Issue by raould** [underscorediscovery/luxe#318]
I prefer to use import luxe.* but that doesn't work to get all the secret typedefs, so apparently i have to go and manually do import luxe.Text and import luxe.Input and etc. which personally i find to be a big drag. €0.02

**Comment by underscorediscovery** [comment]
I prefer you know where things are located and I don't encourage importing entire codebases, conflicts arise too quickly and they are hard for beginners to track down or understand.
