### ISSUE TITLE
Screen; web; cursor visible affects page not canvas

### ISSUE THREAD

**Issue by ImDeity** [underscorediscovery/luxe#319]
Setting `Luxe.screen.cursor.visible = false` on web causes the cursor to disappear for the entire page (even outside the game area). A more user-friendly way would be to only have it disappear while the cursor is over the canvas and have it reappear outside the bounds of the canvas.

**Comment by underscorediscovery** [comment]
This behaviour matches parity with the native API's actually. Window events for enter/leave can be used to toggle the state if the application wants that behaviour instead
