### ISSUE TITLE
tests/rendering/depth: Key.minus and Key.equals values in Keycodes.hx don't match up to reality

### ISSUE THREAD

**Issue by prime31** [underscorediscovery/luxe#328]
Looking through the tests and demos I came across the rendering/depth test. On a MacBook I am getting the following when tracing e.keyCode in the onkeyup method:

'=' is 187
'-' is 189

Key.equals is defined as 61
Key.minus is defined as 45

Also, I assume the 'if' statement checking for Key.space wants to reset the depth to 0 when right now it just sets the depth to itself which doesn't do anything. The contents of the if block should be:

    sprites[0].depth = 0;

Note: once I figure out how to get a Git pull of Luxe working I'll submit proper pull requests for code changes. My apologies for submitting the last part of this in a bug report.

**Comment by underscorediscovery** [comment]
I can only guess you were you running on the web target? What browser + version, language locale, and OS were you running if so?

**Comment by prime31** [comment]
Web target. That is correct. Tested in Safari 9.0 and Chrome 46.0.2490.33 beta. Below is a dump of a request Chrome with locale/OS info:

Accept-Language: en-US,en;q=0.8
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.33 Safari/537.36
