### ISSUE TITLE
All the on* methods in luxe.Game should be attributed with @:noCompletion

### ISSUE THREAD

**Issue by prime31** [underscorediscovery/luxe#329]
Starting with [this method](https://github.com/underscorediscovery/luxe/blob/master/luxe/Game.hx#L32) all the way down the method list. This will keep it inline with Component and the other classes in Luxe that have methods that are intended to be overridden by subclasses attributed.

**Comment by underscorediscovery** [comment]
While the consistency is correct, the outcome of this change would have a negative effect on the documentation and usability. Currently the doc generator respects noCompletion – this would remove any API endpoint for users to look up the core event functions (which starts with their empty app extending `luxe.Game`).

For now, I am going to close both the PR and the issue but I am aware of the inconsistency and steps are being taken (on the code docs, the doc generator, and the plugins/display) to clarify this first.
