### ISSUE TITLE
Post effects; implement render chain

### ISSUE THREAD

**Issue by underscorediscovery** [underscorediscovery/luxe#33]
Usually I prefer to manage this but having a simple built in effect queue with in/out would be a win.

**Comment by anissen** [comment]
Why has this issue been closed? It's something that I would really like to see but it doesn't seem to be implemented yet.

For my [LD34 game](https://github.com/anissen/ld34) I wanted to do some shaders and ended up using [this](https://github.com/FuzzyWuzzie/RegisAgro/blob/master/src/effects/Effects.hx) approach from FuzzyWuzzie. It worked but was not easy to work with and required some work-arounds.

A simple out-of-the-box solution for handling chains of post-processing effects would be awesome.

**Comment by underscorediscovery** [comment]
The issue belongs on the new renderer, the concept will carry :)

**Comment by anissen** [comment]
That's good to hear, thanks! :+1:
