### ISSUE TITLE
SpriteAnimation "skips" first frame

### ISSUE THREAD

**Issue by MicUurloon** [underscorediscovery/luxe#334]
The first frame of an animation is skipped.
I think this is because of this line: https://github.com/underscorediscovery/luxe/blob/master/luxe/components/sprite/SpriteAnimation.hx#L424
Because the 'next_frame_time' is set to 'time' the condition in 'update()' is valid:
https://github.com/underscorediscovery/luxe/blob/master/luxe/components/sprite/SpriteAnimation.hx#L255-L258
So it will continue to the next frame immediately.

Example in a simple project. 
If all was right you should see a '1', then a '2', then a '1' and then a '2' again. All frame with speed 1, so every second a new frame.
Because the first frame is skipped the animation starts with a '2'.
See https://dl.dropboxusercontent.com/u/16579573/animation/index.html

Used animation json:
```
"testanim" : {
				"frame_size":{ "x":"200", "y":"200" },
				"frameset": ["2", "3", "2", "3"],
				"loop": "false",
				"speed": "1"
			}
```

**Comment by underscorediscovery** [comment]
Can you past the example code as well?

**Comment by MicUurloon** [comment]
Source of example:
https://github.com/MicUurloon/Animation

**Comment by underscorediscovery** [comment]
Perfect, nice catch. I wanted to confirm something against a previous bug but you were right in this case (PR's like this are welcome btw, especially with a test case because confirming them against the test and the existing `tests/` are easy to validate)
