### ISSUE TITLE
Text; Missing a pixel perfect flag

### ISSUE THREAD

**Issue by EduardoLopes** [underscorediscovery/luxe#336]
When align is set to `center`, the text doesn't work pixel perfectly. See the example: 
![should show 100](http://i.imgur.com/dw0biMr.png)
The text in the object with a red outline is "100".

The problem only shows if the zoom is equal 1 (that the pixels are too small), if i set the zoom to 2, it doesn't show any problem.

**Comment by underscorediscovery** [comment]
should be addressed by this, we'll add a test soon https://github.com/underscorediscovery/luxe/commit/5c4afc85a9e460374e2ecc44a417d6d5cf566a0a
