### ISSUE TITLE
phoenix; Viewport not reset after resetting render.target

### ISSUE THREAD

**Issue by ivcoar** [underscorediscovery/luxe#342]
Setting the render target to null doesn't reset the viewport, using the width and height of the RenderTexture. This is the result: 
![Bug](http://i.imgur.com/YwFZmUs.png)
And this is how it should look:
![Fix](http://i.imgur.com/AtC32JP.png)
[This is the test I used.](https://gist.github.com/ivcoar/bdd347acb1a3b4b04d4d)

**Comment by underscorediscovery** [comment]
Interesting find.
There is one thing to note: the viewport is set by the batcher `view` camera _when it's rendering_. Just setting the target or unsetting won't set the viewport (and shouldn't). I'll have a closer look at the specific test case soon though, thanks!
