### ISSUE TITLE
Luxe.draw.pie missing

### ISSUE THREAD

**Issue by AbelToy** [underscorediscovery/luxe#343]
So, there's a mention of Pie here: http://luxeengine.com/docs/guide.drawing.html

But it's nowhere to be seen in the code...

**Comment by underscorediscovery** [comment]
ah, just a documentation error, use draw circle/ring with the start/end angle options.

**Comment by AbelToy** [comment]
Cool, thanks!

**Comment by underscorediscovery** [comment]
(We'll make a doc pass after the next alpha milestone and clear that up)
