### ISSUE TITLE
onmousewheel does not have correct event in web browser.

### ISSUE THREAD

**Issue by Mixerman123** [underscorediscovery/luxe#346]
If onmousewheel is overridden in your game class, the Y property of the event (the scroll factor) should show the relative mouse scroll. This works on native targets however does not work in the web browser. In the web browser, the Y property is always 0. The function is still called however.

**Comment by Mixerman123** [comment]
Just realised this is actually already an issue on flow - It's due to inconsistencies in browsers. Sorry - Closing.

**Comment by underscorediscovery** [comment]
No worries, actually it should be an issue on the snow repo, and I've since resolved this and should be upstream soon
