### ISSUE TITLE
Text; Modifying outline_color properties has no effect

### ISSUE THREAD

**Issue by kevinresol** [underscorediscovery/luxe#348]
Works: `text.outline_color = new Color(1,1,1,1);`
Doesn't work: `text.outline_color.rgb(0xffffff);`

Probably because the value isn't updated to the shader.

**Comment by underscorediscovery** [comment]
yea that's because `outline_color` is setter, you can use `text.outline_color = text.outline_color.rgb(0xffffff);` to call the setter for now
