### ISSUE TITLE
App crashes trying to load a texture on windows

### ISSUE THREAD

**Issue by josuigoa** [underscorediscovery/luxe#354]
I've isolated a demo [here](https://github.com/josuigoa/luxe_jpg_error). If you comment [this line](https://github.com/josuigoa/luxe_jpg_error/blob/master/src/Main.hx#L15), it works normally.

I works well on web but crashes on windows.

**Comment by underscorediscovery** [comment]
I had a look quick as it doesn't crash on my mac either,
The strange thing is that it crashes inside OpenGL - right after the submission to the GPU. Just before submission it checks the maximum texture sizes (mine is 16384), so it's not that - it seems that something nuanced is going on outside of the norm here. 

![crash](https://cloud.githubusercontent.com/assets/236374/13159479/a52ace78-d66c-11e5-9522-d08a3e3d469e.jpg)

I'll have a closer look soon as I can, and try changing the file, checking the flags for sanity, that kinda thing.

**Comment by NtrfAtZNS** [comment]
I had the same issue today with /tests/three/mesh_component/ project. When tower.jpg is loaded by snow, it has 3 bytes-per-pixel format and data size of 786432 bytes. This info is outputed by `Texture.dump_asset_info`. However when texture is uploaded into the GPU with `GL.texImage2D` format is specified as GL_RGBA, which expects 4 bytes-per-pixel and 1048576 bytes of data. This causes crash in `nvogl32` system library. Changing image to PNG 32bit fixes the issue.

**Comment by underscorediscovery** [comment]
Ah good point @NtrfAtZNS, I think I can fix this pretty easily, there seems to be a discontinuity between the values.

```
Texture.hx:319:   i / texture / Texture Asset id: assets/front.jpg
Texture.hx:320:   i / texture / 	 image.bpp: 4
Texture.hx:321:   i / texture / 	 image.bpp_source: 3
Texture.hx:322:   i / texture / 	 image.pixels.length: 9558000
Texture.hx:323:   i / texture / 	 image.height: 2124
Texture.hx:324:   i / texture / 	 image.height_actual: 2124
Texture.hx:325:   i / texture / 	 image.width: 1500
Texture.hx:326:   i / texture / 	 image.width_actual: 1500
```

With `1500 * 2124 * 3` it's `9,558,000` but the actual bpp is meant to be 4 (stb image will convert it to a requested bpp of 4 by default) which should be `12,744,000`, so it seems that this is the cause.

**Comment by underscorediscovery** [comment]
I'm sure this fixes it https://github.com/snowkit/linc_stb/commit/6a98e15982c6dd13927eee0470c15e5b33b9f747

@NtrfAtZNS @josuigoa let me know by updating [linc_stb](https://github.com/snowkit/linc_stb) (you can try [snowfall](http://snowkit.org/2016/02/17/snowfall/) if you haven't)

**Comment by josuigoa** [comment]
yes, it's working!! this error was so deep for me...
thanks a lot @NtrfAtZNS and @underscorediscovery !

**Comment by underscorediscovery** [comment]
Thanks for reporting too!
