### ISSUE TITLE
Input; all touch inputs report same touch_id

### ISSUE THREAD

**Issue by jonathanhirz** [underscorediscovery/luxe#355]
https://github.com/jonathanhirz/touch_id_bug (all this does is trace e.touch_id on ontouchdown())

Expecting: each touch, single and multiple, to receive unique touch_ids

Seeing: All touches are assigned the same id.

Tested on Macbook trackpad and iPhone 6 hardware.

**Comment by underscorediscovery** [comment]
What was the id that you're seeing (is it a long random number or 0 or)?

**Comment by jonathanhirz** [comment]
on mac, it's an 8 digit number that's different each time I compile (but the same on every touch while running). On iPhone it's always 1.

**Comment by underscorediscovery** [comment]
update snow (or run [snowfall](http://snowkit.org/2016/02/17/snowfall/)) should fix it

**Comment by jonathanhirz** [comment]
Thank you!
