### ISSUE TITLE
phoenix.Matrix; Typo in up function

### ISSUE THREAD

**Issue by NtrfAtZNS** [underscorediscovery/luxe#357]
Method `up` reports wrong data. There is a typo in the source code - wrong matrix component returned:

```
    public inline function up() {
        return new Vector( elements[4], elements[5], elements[10] );
    } //up
```
Z coordinate sould be `elements[6]` instead of `elements[10]`.

**Comment by underscorediscovery** [comment]
Well spotted, the new maths classes in embers have unit tests to validate silly things like this.
Thanks!
