### ISSUE TITLE
Exception when starting app on ios

### ISSUE THREAD

**Issue by thealgebraist** [underscorediscovery/luxe#363]
When running my project on my ipad I get this exception:

Core.hx:267:      i / luxe / config / preload / failed to load
libc++abi.dylib: terminating with uncaught exception of type Dynamic

Any idea what causes this?

**Comment by underscorediscovery** [comment]
If you're running with the debug scheme it should print a normal haxe stack trace into the debug log window. It should also crash with a callstack on the debug screen.

**Comment by thealgebraist** [comment]
You were right - it was caused by trying to load a missing file at startup.

**Comment by underscorediscovery** [comment]
Glad you got by!
