### ISSUE TITLE
Visual clears individual vertex colors in geometry

### ISSUE THREAD

**Issue by hedgehog90** [underscorediscovery/luxe#371]
I'm trying to draw a poly with a color for each vertex in the instantiation of a Visual. But by default, Visual assumes every vertex is the same color, so even if I defined colors in Geometry it overrides them. The first thing Visual does is erase all the indiviual colors, and there's no way to prevent this it seems without changing the code in Visual.hx.
Is my approach to this wrong-headed or is this a slight design flaw?
If i just call Luxe.draw.poly without attaching it to a visual then it works fine, but I'd like to easily move it about as a visual.

Here's an example:

	var visual:Visual = new Visual({
		geometry : Luxe.draw.poly({
			solid : true,
			colors: [
				new Color().rgb(0xff0000),
				new Color().rgb(0xff0000),
				new Color().rgb(0x0000ff),
				new Color().rgb(0x0000ff)
			],
			points: [
				new Vector(0, 0),
				new Vector(400, 0),
				new Vector(400, 400),
				new Vector(0, 400)
			]
		})
	});

**Comment by underscorediscovery** [comment]
see here: https://github.com/underscorediscovery/luxe/blob/master/luxe/Visual.hx#L295-L312

The shortest path without trying to hack around it just set the vert polys after create:
`visual.geometry.vertices[0].color = new Color().rgb(0xff0000)`

I know it's not ideal, hence the alpha, all the rendering stuff is changing with the new renderer so this type of thing would be resolved when switching.
