### ISSUE TITLE
phoenix; RenderTexture; non-existent renderbuffer on iOS

### ISSUE THREAD

**Issue by kneeko** [underscorediscovery/luxe#375]
The /tests/rendering/rendertexture project reproduces this issue. Here's the error and GL calls from Xcode:

```
Attempted present of non-existent renderbuffer (Issue) Renderbuffer #0 can not be presented as it is a non-existent renderbuffer
```

```
#0 glClearColor(0.1019608, 0.1019608, 0.1019608, 1.0000000)
#1 glClear(GL_COLOR_BUFFER_BIT)
#2 glViewport(0, 0, 1536, 2048)
#3 glBindTexture(GL_TEXTURE_2D, 3)
#4 projectionMatrix <- glGetUniformLocation(6, "projectionMatrix")
#5 modelViewMatrix <- glGetUniformLocation(6, "modelViewMatrix")
#6 glUseProgram(6)
#7 glUniformMatrix4fv(modelViewMatrix, 1, 0, {1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000})
#8 glUniformMatrix4fv(projectionMatrix, 1, 0, {0.0013021, 0.0000000, 0.0000000, 0.0000000, 0.0000000, -0.0009766, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0010000, 0.0000000, -1.0000000, 1.0000000, 0.0000000, 1.0000000})
#9 glGenBuffers(1, {7})
#10 glGenBuffers(1, {8})
#11 glGenBuffers(1, {9})
#12 glBindBuffer(GL_ARRAY_BUFFER, 7)
#13 glVertexAttribPointer(0, 4, GL_FLOAT, 0, 0, NULL)
#14 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#15 glBindBuffer(GL_ARRAY_BUFFER, 9)
#16 glVertexAttribPointer(1, 4, GL_FLOAT, 0, 0, NULL)
#17 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#18 glBindBuffer(GL_ARRAY_BUFFER, 8)
#19 glVertexAttribPointer(2, 4, GL_FLOAT, 0, 0, NULL)
#20 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#21 glDrawArrays(GL_TRIANGLES, 0, 6)
#22 glDeleteBuffers(1, {7})
#23 glDeleteBuffers(1, {8})
#24 glDeleteBuffers(1, {9})
#25 glBindTexture(GL_TEXTURE_2D, 0)
#26 glUseProgram(0)
#27 glBindFramebuffer(GL_FRAMEBUFFER, 2)
#28 glClearColor(1.0000000, 0.2941177, 0.0117647, 1.0000000)
#29 glClear(GL_COLOR_BUFFER_BIT)
#30 glViewport(0, 0, 512, 512)
#31 glBindTexture(GL_TEXTURE_2D, 2)
#32 projectionMatrix <- glGetUniformLocation(6, "projectionMatrix")
#33 modelViewMatrix <- glGetUniformLocation(6, "modelViewMatrix")
#34 glUseProgram(6)
#35 glUniformMatrix4fv(modelViewMatrix, 1, 0, {1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 1.0000000})
#36 glUniformMatrix4fv(projectionMatrix, 1, 0, {0.0039062, 0.0000000, 0.0000000, 0.0000000, 0.0000000, -0.0039062, 0.0000000, 0.0000000, 0.0000000, 0.0000000, 0.0010000, 0.0000000, -1.0000000, 1.0000000, 0.0000000, 1.0000000})
#37 glGenBuffers(1, {7})
#38 glGenBuffers(1, {8})
#39 glGenBuffers(1, {9})
#40 glBindBuffer(GL_ARRAY_BUFFER, 7)
#41 glVertexAttribPointer(0, 4, GL_FLOAT, 0, 0, NULL)
#42 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#43 glBindBuffer(GL_ARRAY_BUFFER, 9)
#44 glVertexAttribPointer(1, 4, GL_FLOAT, 0, 0, NULL)
#45 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#46 glBindBuffer(GL_ARRAY_BUFFER, 8)
#47 glVertexAttribPointer(2, 4, GL_FLOAT, 0, 0, NULL)
#48 glBufferData(GL_ARRAY_BUFFER, 96, <data>, GL_STREAM_DRAW)
#49 glDrawArrays(GL_TRIANGLES, 0, 6)
#50 glDeleteBuffers(1, {7})
#51 glDeleteBuffers(1, {8})
#52 glDeleteBuffers(1, {9})
#53 glBindTexture(GL_TEXTURE_2D, 0)
#54 glUseProgram(0)
#55 glBindFramebuffer(GL_FRAMEBUFFER, 0)
#56 ["Context 1" presentRenderbuffer:GL_RENDERBUFFER]
```

**Comment by underscorediscovery** [comment]
could you specify which device (or simulator?), OS version etc as to narrow it down?  Thanks!

**Comment by kneeko** [comment]
The above calls are from an iPad mini 2 running 9.3.1. I think I see the same issue (black screen) on the simulator (iPhone 6, iPad 2), but as far as I know it is not possible to launch the GPU debugger on the simulator to confirm. I believe @nslottow has seen the same issue on his iPhone 6 presumably running 9.0+. for what it's worth, those same devices are able to run the same project via the web target.

**Comment by underscorediscovery** [comment]
Thanks, I'll have a look later. I don't think much if anything changed there, so it seems to be rather odd. (I've been working on the new renderer, phoenix is going away soon enough, but I'll be sure to test both anyway)

**Comment by ntrf** [comment]
iOS never had framebuffer 0. Every app is rendered into its own framebuffer, which is configured with [system API](https://developer.apple.com/library/ios/documentation/OpenGLES/Reference/EAGLContext_ClassRef/index.html#//apple_ref/occ/instm/EAGLContext/renderbufferStorage:fromDrawable:), instead of being preallocated by system. This is one of the differences from standard OpenGL. When using third-party libs to create GL context (SDL, GLFW or other) you don't have handle to that frameuffer, as it stays inside the lib. Usually there is a [library function](https://developer.apple.com/library/ios/documentation/GLkit/Reference/GLKView_ClassReference/index.html#//apple_ref/occ/instm/GLKView/bindDrawable), that binds the screen framebuffer, but i can't find one for SDL. You can get handle of screen framebuffer by using `glGetInteger` after you create and bind SDL context, [like SDL itself does for some reason](https://github.com/native-toolkit/sdl/blob/master/src/render/opengles2/SDL_render_gles2.c#L2072).

**Comment by underscorediscovery** [comment]
Yes [this](https://github.com/underscorediscovery/luxe/blob/master/phoenix/Renderer.hx#L81) is not the issue, this has worked all along. This is anomalous.

**Comment by underscorediscovery** [comment]
@kneeko thanks for the report, it's been fixed. Update `linc_opengl` (using snowfall or directly) should solve it.
