### ISSUE TITLE
Degrees or Radians

### ISSUE THREAD

**Issue by buckle2000** [underscorediscovery/luxe#377]
Is there a way to change the whole luxe engine to use radians?
Changing `_180_OVER_PI` to **1**?

**Comment by underscorediscovery** [comment]
The concept is a bit strange as there isn't much in the way of predefined angle. Where are you finding degrees that doesn't have radians?

**Comment by buckle2000** [comment]
Because using radians in computing is faster and easier.

**Comment by buckle2000** [comment]
And I just don't understand why there is both code for deg and rad:
```
    function set_rotation_z( _degrees:Float ) : Float {

        radians = Maths.radians(_degrees);

        return _degrees;

    } //set_rotation_z
```

**Comment by underscorediscovery** [comment]
Ah I see. There are many cases where degrees might be favoured over radians and vice versa. luxe is designed to facilitate, and this type of facilitation is a good example of facilitating a frequent need for 2D visuals. You just use whichever one is most appropriate for your situation, and internally everything is radians.
