### ISSUE TITLE
Camera; Setting Luxe.camera.size zooms out camera

### ISSUE THREAD

**Issue by BrodyB** [underscorediscovery/luxe#378]
When setting the screen size to a resolution (say, 1280x720) in project.flow, and then setting Luxe.camera.size to a vector of that same size in your Main ready() method, the camera appears zoomed out when running the game. Ideally, the window and the camera resolution should be the same as long as the user hasn't resized the window.

![Camera Size Not Set](https://cloud.githubusercontent.com/assets/2968043/15059424/691d8784-12d7-11e6-87e9-adc7833b7246.png)
![Camera Size Set](https://cloud.githubusercontent.com/assets/2968043/15059428/6efde310-12d7-11e6-8c8a-315cd7ffe37e.png)

**Comment by underscorediscovery** [comment]
p.s this was related to https://github.com/underscorediscovery/luxe/issues/379
Since the sizes weren't applied they don't align!
