### ISSUE TITLE
Android audio

### ISSUE THREAD

**Issue by CamperPR** [underscorediscovery/luxe#381]
So, i have a problem: sounds on android dont working. Instead them i hear only loop of half second of begining.

I took a code from samples on luxe site
>  theme = Luxe.resources.audio("assets/shop.wav");
    theme_handle = Luxe.audio.loop(theme.source);

P.S. Sry for my english.

**Comment by underscorediscovery** [comment]
Can you run `luxe/tests/features/audio` and see if you see the same?

**Comment by CamperPR** [comment]
No, there everything is ok!

**Comment by underscorediscovery** [comment]
I'm not sure exactly, if you can make a simple test that shows the error I can have a look for you
