### ISSUE TITLE
Degree / Radian inconsistency

### ISSUE THREAD

**Issue by PentaHelix** [underscorediscovery/luxe#382]
Using Quaternion.toeuler() returns a Vector of the rotation in degrees, but using Quaternion.setFromEuler() requieres a Vector of radians.

**Comment by underscorediscovery** [comment]
Thanks for the note! I've been making sure the new maths classes are consistent (and easier to use). Since phoenix isn't sticking around, this isn't an issue I need to keep track of so I'll close it for now
