### ISSUE TITLE
Luxe Fails to Compile on Windows 10 After Recent Hxcpp Update

### ISSUE THREAD

**Issue by DeejStar** [underscorediscovery/luxe#385]
I get this error when I previously had no issues before:

http://pastebin.com/RMepufi0

I'm using Visual Studio 2015 Community with all of the prerequisites installed. I haven't tried with the recommended version from Haxelib (Visual C++ 2010).

**Comment by Draygera** [comment]
The latest update to hxcpp seems to have broken building and running on Windows. Not sure what changed with it

**Comment by ntrf** [comment]
That is MSVS-specific problem. As a temporary workaround turn off precompiled headers in `.hxcpp_config.xml`. Compilation will take more time, but at least it will work.

**Comment by Draygera** [comment]
Thanks. Will try that.

**Comment by ntrf** [comment]
It's in your user folder. `C:\Users\<username>\.hxcpp_config.xml` on windows or `~/.hxcpp_config.xml` on mac/*nix.

**Comment by Draygera** [comment]
Thanks. XD

**Comment by underscorediscovery** [comment]
Thanks for the report, and the help ntrf. Also thanks for reporting on hxcpp side.
Did you get by at least?

**Comment by Draygera** [comment]
I hadn't actually gotten around to fully testing it. I'm about to.

**Comment by underscorediscovery** [comment]
No rush, just checking in.

**Comment by Draygera** [comment]
@ntrf's suggestion worked. Although, I will say, I'd love to use MingW for this instead of VS 2015, but that's a preference thing.

**Comment by hughsando** [comment]
"#include <hxcpp.h>" needs to be the first non-trivial line in a file if you want pre-compiled headers and compile your code at the same time as haxe-gen code.
Alternatively, you can opt-out of PCH (as you have done).  You can also opt-out on a file-by-file basis, but I think it is best to just go with it, and move the include to the top.

**Comment by kevinresol** [comment]
If anyone is struggling about how to disable PCH, just add the following to your .hxcpp_config.xml
```xml
<set name="NO_PRECOMPILED_HEADERS" value="1"/>
```

**Comment by xiggie** [comment]
What happens when "NO_PRECOMPILED_HEADERS" is enabled, but it still produces the error?

**Comment by DragOnGamer626** [comment]
Actually, after recent updates, I had to disable that to get it to compile again. So whatever was done, it seemed to fix the issue so far. :D

**Comment by underscorediscovery** [comment]
If anyone is still having trouble on 3.4 with everything updated, I can reopen this. Just let me know.
