### ISSUE TITLE
Calling destroy(true) on an Entity doesn't remove it from its parent?

### ISSUE THREAD

**Issue by wetlag** [underscorediscovery/luxe#386]
Not sure if I'm missing something dumb or misinterpreting something, but in

public function destroy( ?_from_parent:Bool=false )

there's this part 

        if(parent != null && !_from_parent) {
            _verbose("     removing " + name + "/" + id + " from parent " + parent.name + " / " + parent.id );
            parent._remove_child(this);
        }

So if _from_parent is true, the parent will not remove the child?

Does _from_parent mean it should be removed from parent if true? Or does it mean something else?

**Comment by underscorediscovery** [comment]
It's an internal flag iirc, you probably shouldn't be calling it with that (it's a wip solution to something else).
What are you trying to do, rather?

**Comment by wetlag** [comment]
Ah okay. I thought I had to call it with true if I wanted to remove it from the parent. But just calling destroy() is fine.

Thanks!
