### ISSUE TITLE
Web browser that doesn't support webkit audio

### ISSUE THREAD

**Issue by Jumblemuddle** [underscorediscovery/luxe#399]
Doesn't seem like luxe works on web browsers that don't support webkit audio api.

`TypeError: undefined is not a constructor (evaluating 'new window.webkitAudioContext()')`

Works fine in Chrome, but Qutebrowsers seems to break it. I'd assumed the audio simply wouldn't work since the api isn't implemented.

**Comment by underscorediscovery** [comment]
Thanks for the report, I had this reported recently and it should be resolved quickly.

**Comment by underscorediscovery** [comment]
@Jumblemuddle since you have a browser that exhibits this, can you update (say via `snowfall update luxe`) and test if it at least doesn't crash out for you now?

**Comment by Jumblemuddle** [comment]
Hey, @underscorediscovery, sorry for the delayed reponse. Works like a charm! Thanks!
