### ISSUE TITLE
Shutdown fails

### ISSUE THREAD

**Issue by CamperPR** [underscorediscovery/luxe#404]
I tested shutdown function in my project and luxe's tests. So, on the web it outputs this: `Uncaught TypeError: Array.prototype.indexOf called on null or undefined`,
on the windows: 

> Called from luxe.Game::main luxe/Game.hx line 18
> Called from Main::new Main.hx line 7
> Called from luxe.Game::new luxe/Game.hx line 26
> Called from luxe.Engine::run luxe/Engine.hx line 94
> Called from snow.Snow::new snow/Snow.hx line 143
> Called from snow.modules.sdl.Runtime::run snow/modules/sdl/Runtime.hx line 100
> Called from snow.modules.sdl.Runtime::run_loop snow/modules/sdl/Runtime.hx line 183
> Called from snow.modules.sdl.Runtime::loop snow/modules/sdl/Runtime.hx line 208
> Called from snow.Snow::dispatch_event snow/Snow.hx line 188
> Called from snow.Snow::onevent snow/Snow.hx line 235
> Called from snow.Snow::shutdown snow/Snow.hx line 166
> Called from luxe.Engine::ondestroy luxe/Engine.hx line 188
> Called from luxe.Emitter::emit luxe/Emitter.hx line 72
> Called from luxe.Scene::_destroy luxe/Scene.hx line 395
> Called from luxe.Scene::destroy luxe/Scene.hx line 442
> Called from luxe.Emitter::emit luxe/Emitter.hx line 80
> Called from luxe.Emitter::_check luxe/Emitter.hx line 171
> AL lib: (EE) alc_cleanup: 1 device not closed

**Comment by jonathanhirz** [comment]
Yay! Someone else who is seeing this error too. I get this when shutting down on Mac.

> flow / build - done
> flow / launching spaceRL 0.0.1 for mac
> 
> Engine.hx:148:    i / luxe / 1.0.0-alpha.3+e2c1172033 / debug:true / os:mac / platform:mac
> Engine.hx:292:    i / luxe / opengl  / 2.1 INTEL-10.2.10 / 1.20 / Intel HD Graphics 3000 OpenGL Engine / Intel Inc. / 
> Engine.hx:185:    i / luxe / shutting down...
> Called from luxe.Game::main luxe/Game.hx line 18
> Called from Main::new Main.hx line 9
> Called from luxe.Game::new luxe/Game.hx line 26
> Called from luxe.Engine::run luxe/Engine.hx line 94
> Called from snow.Snow::new snow/Snow.hx line 143
> Called from snow.modules.sdl.Runtime::run snow/modules/sdl/Runtime.hx line 100
> Called from snow.modules.sdl.Runtime::run_loop snow/modules/sdl/Runtime.hx line 183
> Called from snow.modules.sdl.Runtime::loop snow/modules/sdl/Runtime.hx line 208
> Called from snow.Snow::dispatch_event snow/Snow.hx line 188
> Called from snow.Snow::onevent snow/Snow.hx line 235
> Called from snow.Snow::shutdown snow/Snow.hx line 166
> Called from luxe.Engine::ondestroy luxe/Engine.hx line 188
> Called from luxe.Emitter::emit luxe/Emitter.hx line 72
> Called from luxe.Scene::_destroy luxe/Scene.hx line 395
> Called from luxe.Scene::destroy luxe/Scene.hx line 442
> Called from luxe.Emitter::emit luxe/Emitter.hx line 80
> Called from luxe.Emitter::_check luxe/Emitter.hx line 171
> Error : Null Object Reference

**Comment by underscorediscovery** [comment]
I love that the issue number is 404 ... 
Thanks for the report.
