### ISSUE TITLE
VSCode Extension

### ISSUE THREAD

**Issue by slothh** [underscorediscovery/luxe#429]
I was wondering if it was possible for someone to develop a visual studio code extension for the luxe engine. I really enjoy using it, but having VSCode throw errors at me all the time is really annoying...

**Comment by underscorediscovery** [comment]
Could you at least say _what_ errors you're getting, not just that you're getting them? 

I've made some notes on the IDE setup page, see if doing it this way helps for you.

https://luxeengine.com/setup-an-ide/#vscode

**Comment by slothh** [comment]
Very sorry for not posting that originally. I was just talking about code completion errors, like the red-squiggly lines underneath words. I will configure the code completion tomorrow. I'm new to posting about issues and on forums at all, sorry for any inconveniences.

**Comment by underscorediscovery** [comment]
That's ok! I like to help but I have nothing to go on :)
Let me know how you get by though.

**Comment by Gama11** [comment]
@underscorediscovery You may wanna update the `tasks.json` example, the `problemMatcher` can just reference the one included in vshaxe since version 1.5.0 with `"problemMatcher": "$haxe"`.

See https://github.com/vshaxe/vshaxe/wiki/Build-Tasks.

**Comment by underscorediscovery** [comment]
@Gama11 I got this from the latest vscode the same time I commented, is this new? I'll update it soon.

**Comment by Gama11** [comment]
As I said, since vshaxe version 1.5.0 - which was released April 7th.

**Comment by underscorediscovery** [comment]
Strange! I literally installed latest vscode, then latest vshaxe, and then "Haxe: Initialize VS Code Project" which I copy pasted from - just 3 days ago. 

I did it from scratch now I get the newer one... No idea what happened there but the guide is updated thanks.
